# Generated by Django 6.1.1 on 2026-09-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_evento_necessita_comprovante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="local_tipo",
            field=models.CharField(
                choices=[
                    ("Auditório", "Auditório"),
                    ("Sala", "Sala"),
                    ("Laboratório", "Laboratório"),
                    ("Outro", "Outro"),
                ],
                default="Auditório",
                max_length=50,
                verbose_name="Tipo de Local",
            ),
        ),
    ]
