# Generated by Django 6.1.1 on 2026-09-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="necessita_comprovante",
            field=models.BooleanField(
                default=False,
                help_text="Define se o evento necessita ou não de comprovante",
                verbose_name="Comprovante",
            ),
        ),
    ]
