# Generated by Django 6.1.1 on 2026-09-26 20:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0002_evento_necessita_comprovante"),
        ("inscricao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPreco",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Estudante, Profissional, Geral, VIP",
                        max_length=100,
                        verbose_name="Nome da Categoria",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, default="", verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_preco",
                        to="eventos.evento",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Preço",
                "verbose_name_plural": "Categorias de Preço",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Certificado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_autenticacao",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        max_length=100,
                        unique=True,
                        verbose_name="Código de Autenticação",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificados/",
                        verbose_name="Arquivo do Certificado (PDF)",
                    ),
                ),
                (
                    "disponivel",
                    models.BooleanField(
                        default=False,
                        help_text="Habilitado quando cumpridas as condições de participação e confirmação de presença.",
                        verbose_name="Disponível para Emissão",
                    ),
                ),
                (
                    "carga_horaria",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Carga Horária (horas)"
                    ),
                ),
                (
                    "emitido_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Emitido em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "inscricao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificado",
                        to="inscricao.inscricao",
                        verbose_name="Inscrição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["-emitido_em"],
            },
        ),
        migrations.CreateModel(
            name="Cobranca",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor Original",
                    ),
                ),
                (
                    "valor_final",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor Final",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGA", "Paga"),
                            ("CANCELADA", "Cancelada"),
                            ("EXPIRADA", "Expirada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status da Cobrança",
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateTimeField(verbose_name="Data de Vencimento"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cobrancas",
                        to="inscricao.inscricao",
                        verbose_name="Inscrição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cobrança",
                "verbose_name_plural": "Cobranças",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Comunicacao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        default="EMAIL",
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                ("assunto", models.CharField(max_length=255, verbose_name="Assunto")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                ("enviado", models.BooleanField(default=False, verbose_name="Enviado")),
                (
                    "data_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Envio"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "certificado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comunicacoes",
                        to="pagamentos.certificado",
                        verbose_name="Certificado Relacionado",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comunicacoes_recebidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicação",
                "verbose_name_plural": "Comunicações",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="IsencaoPagamento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("TOTAL", "Total"), ("PARCIAL", "Parcial")],
                        default="TOTAL",
                        max_length=20,
                        verbose_name="Tipo de Isenção",
                    ),
                ),
                (
                    "desconto_percentual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Desconto Percentual (%)",
                    ),
                ),
                (
                    "desconto_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor do Desconto (R$)",
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        help_text="Justificativa para a concessão da isenção ou abatimento.",
                        verbose_name="Motivo / Justificativa",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="isencoes_concedidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "cobranca",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isencao",
                        to="pagamentos.cobranca",
                        verbose_name="Cobrança",
                    ),
                ),
            ],
            options={
                "verbose_name": "Isenção de Pagamento",
                "verbose_name_plural": "Isenções de Pagamento",
            },
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: 1º Lote, Lote Promocional",
                        max_length=100,
                        verbose_name="Nome do Lote",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Número do Lote"
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Preço",
                    ),
                ),
                (
                    "quantidade_total",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade Total",
                    ),
                ),
                (
                    "quantidade_disponivel",
                    models.PositiveIntegerField(
                        help_text="Quantidade de inscrições disponíveis restantes neste lote",
                        verbose_name="Quantidade Disponível",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(verbose_name="Data de Início da Vigência"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(verbose_name="Data de Término da Vigência"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "categoria_preco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotes",
                        to="pagamentos.categoriapreco",
                        verbose_name="Categoria de Preço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "ordering": ["numero", "data_inicio"],
            },
        ),
        migrations.AddField(
            model_name="cobranca",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cobrancas",
                to="pagamentos.lote",
                verbose_name="Lote Aplicado",
            ),
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("PIX", "Pix"),
                            ("CARTAO_CREDITO", "Cartão de Crédito"),
                            ("CARTAO_DEBITO", "Cartão de Débito"),
                            ("BOLETO", "Boleto Bancário"),
                        ],
                        max_length=20,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("APROVADO", "Aprovado"),
                            ("RECUSADO", "Recusado"),
                            ("CANCELADO", "Cancelado"),
                            ("REEMBOLSADO", "Reembolsado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status do Pagamento",
                    ),
                ),
                (
                    "transacao_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Código retornado pelo Gateway/PSP",
                        max_length=255,
                        verbose_name="ID da Transação",
                    ),
                ),
                (
                    "gateway_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Gateway / PSP",
                    ),
                ),
                (
                    "detalhes_processamento",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Retorno e metadados da transação fornecidos pelo gateway",
                        verbose_name="Detalhes do Processamento",
                    ),
                ),
                (
                    "qr_code_pix",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Payload Copia e Cola / QR Code Pix",
                    ),
                ),
                (
                    "url_pagamento",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="URL de Redirecionamento / Boleto",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Confirmação do Pagamento",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "cobranca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="pagamentos.cobranca",
                        verbose_name="Cobrança",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Reembolso",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor do Reembolso",
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo do Reembolso")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SOLICITADO", "Solicitado"),
                            ("PROCESSANDO", "Processando"),
                            ("CONCLUIDO", "Concluído"),
                            ("RECUSADO", "Recusado"),
                        ],
                        default="SOLICITADO",
                        max_length=20,
                        verbose_name="Status do Reembolso",
                    ),
                ),
                (
                    "transacao_reembolso_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID do Reembolso no Gateway",
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Solicitação"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "analisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reembolsos_avaliados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Analisado por",
                    ),
                ),
                (
                    "pagamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reembolso",
                        to="pagamentos.pagamento",
                        verbose_name="Pagamento",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reembolsos_solicitados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reembolso",
                "verbose_name_plural": "Reembolsos",
                "ordering": ["-data_solicitacao"],
            },
        ),
    ]
