# Generated by Django 6.1.1 on 2026-09-23 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente_pagamento", "Pendente de Pagamento"),
                            ("confirmada", "Confirmada"),
                            ("lista_espera", "Lista de Espera"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente_pagamento",
                        max_length=20,
                    ),
                ),
                (
                    "comprovante",
                    models.FileField(blank=True, null=True, upload_to="comprovantes/"),
                ),
                (
                    "dados_adicionais",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Respostas para campos personalizados",
                    ),
                ),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to="eventos.evento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "evento")},
            },
        ),
    ]
