# Generated by Django 6.1.1 on 2026-09-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papelcontextual',
            name='evento_id',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='ID do Evento'),
        ),
        migrations.AlterField(
            model_name='perfilorganizador',
            name='bio_do_organizador',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Mini-biografia do Organizador'),
        ),
    ]
