# Generated by Django 6.1.1 on 2026-09-28 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliador",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "lattes_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL do currículo Lattes do avaliador.",
                        max_length=500,
                        verbose_name="Currículo Lattes",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL do perfil LinkedIn do avaliador.",
                        max_length=500,
                        verbose_name="Perfil LinkedIn",
                    ),
                ),
                (
                    "afiliacao_institucional",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Universidade ou instituição de vínculo.",
                        max_length=255,
                        verbose_name="Afiliação Institucional",
                    ),
                ),
                (
                    "maior_titulacao",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Grau acadêmico do avaliador (e.g., Mestrado, Doutorado).",
                        max_length=100,
                        verbose_name="Maior Titulação",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para impedir que este avaliador seja sorteado.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "areas",
                    models.ManyToManyField(
                        help_text="Áreas temáticas em que o avaliador pode atuar.",
                        related_name="avaliadores",
                        to="submissao.area",
                        verbose_name="Áreas de Atuação",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        help_text="Usuário cadastrado como avaliador de submissões.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_avaliador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliador",
                "verbose_name_plural": "Avaliadores",
                "ordering": ["usuario__nome_completo"],
                "indexes": [
                    models.Index(fields=["ativo"], name="submissao_a_ativo_c68b33_idx")
                ],
            },
        ),
    ]
