# Generated by Django 6.1.1 on 2026-09-21 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import usuarios.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(db_index=True, max_length=14, unique=True, validators=[usuarios.validators.validar_cpf], verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso Admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuário')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilOrganizador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='organizadores/fotos/', validators=[usuarios.validators.validar_extensao_imagem], verbose_name='Foto de Perfil')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='organizadores/banners/', validators=[usuarios.validators.validar_extensao_imagem], verbose_name='Banner Visual')),
                ('bio_do_organizador', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Mini-biografia do Organizador')),
                ('homologado', models.BooleanField(default=False, verbose_name='Homologado para Criar Eventos')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_organizador', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Organizador',
                'verbose_name_plural': 'Perfis de Organizadores',
            },
        ),
        migrations.CreateModel(
            name='CodigoRecuperacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6, verbose_name='Código de Verificação')),
                ('canal', models.CharField(default='EMAIL', max_length=20, verbose_name='Canal de Envio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('utilizado', models.BooleanField(default=False, verbose_name='Utilizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Código de Recuperação',
                'verbose_name_plural': 'Códigos de Recuperação',
                'indexes': [models.Index(fields=['usuario', 'codigo', 'utilizado'], name='usuarios_co_usuario_0b67f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PapelContextual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evento_id', models.PositiveBigIntegerField(verbose_name='ID do Evento')),
                ('papel', models.CharField(choices=[('PARTICIPANTE', 'Participante'), ('AUTOR', 'Autor'), ('AVALIADOR', 'Avaliador'), ('ORGANIZADOR', 'Organizador'), ('PALESTRANTE', 'Palestrante'), ('VOLUNTARIO', 'Voluntário'), ('SUPORTE', 'Suporte')], default='PARTICIPANTE', max_length=20, verbose_name='Papel')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atribuido_em', models.DateTimeField(auto_now_add=True, verbose_name='Atribuído em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeis_contextuais', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Papel Contextual',
                'verbose_name_plural': 'Papéis Contextuais',
                'unique_together': {('usuario', 'evento_id', 'papel')},
            },
        ),
    ]
