# Generated by Django 6.1.1 on 2026-09-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'usuarios',
            '0003_alter_codigorecuperacao_id_alter_papelcontextual_id_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='codigorecuperacao',
            name='tentativas',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas Incorretas'),
        ),
    ]
