# Generated by Django 6.1.1 on 2026-09-26 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0002_evento_necessita_comprovante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nome da Área"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descrição detalhada da área temática.",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Área Temática",
                "verbose_name_plural": "Áreas Temáticas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome do Local"),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descrição das características do local.",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "capacidade",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número máximo de pessoas que o local pode acomodar.",
                        null=True,
                        verbose_name="Capacidade",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locais_apresentacao",
                        to="eventos.evento",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local de Apresentação",
                "verbose_name_plural": "Locais de Apresentação",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Submissao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título do trabalho acadêmico.",
                        max_length=300,
                        verbose_name="Título",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descrição adicional sobre o trabalho.",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        help_text="Resumo em inglês ou português conforme normas do evento.",
                        verbose_name="Abstract",
                    ),
                ),
                (
                    "resumo",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Resumo executivo do trabalho.",
                        verbose_name="Resumo",
                    ),
                ),
                (
                    "palavras_chave",
                    models.CharField(
                        help_text="Palavras-chave separadas por vírgula.",
                        max_length=500,
                        verbose_name="Palavras-chave",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Artigo", "Artigo"),
                            ("Palestra", "Palestra"),
                            ("Minicurso", "Minicurso"),
                            ("Poster", "Poster"),
                            ("Outro", "Outro"),
                        ],
                        default="Artigo",
                        max_length=50,
                        verbose_name="Tipo de Submissão",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Rascunho", "Rascunho"),
                            ("Submetida", "Submetida"),
                            ("Em avaliação", "Em avaliação"),
                            ("Correções solicitadas", "Correções solicitadas"),
                            ("Aprovada", "Aprovada"),
                            ("Rejeitada", "Rejeitada"),
                        ],
                        db_index=True,
                        default="Rascunho",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        help_text="Área temática de classificação do trabalho.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissoes",
                        to="submissao.area",
                        verbose_name="Área Temática",
                    ),
                ),
                (
                    "autor_principal",
                    models.ForeignKey(
                        help_text="Usuário responsável pela submissão do trabalho.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissoes_como_autor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor Principal",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        help_text="Evento para o qual o trabalho é submetido.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissoes",
                        to="eventos.evento",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submissão",
                "verbose_name_plural": "Submissões",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status_parecer",
                    models.CharField(
                        choices=[
                            ("Aprovado", "Aprovado"),
                            ("Rejeitado", "Rejeitado"),
                            ("Necessita correção", "Necessita correção"),
                        ],
                        default="Necessita correção",
                        max_length=30,
                        verbose_name="Status do Parecer",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        help_text="Feedback detalhado e observações dos revisores para o autor.",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "pontuacao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nota consolidada dos critérios técnicos.",
                        max_digits=5,
                        null=True,
                        verbose_name="Pontuação",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avaliacoes_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Avaliador",
                    ),
                ),
                (
                    "submissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="submissao.submissao",
                        verbose_name="Submissão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Apresentacao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "inicio",
                    models.DateTimeField(
                        help_text="Data e horário agendado para a apresentação.",
                        verbose_name="Data e Horário de Início",
                    ),
                ),
                (
                    "duracao_minutos",
                    models.PositiveIntegerField(
                        help_text="Duração estimada da apresentação em minutos.",
                        verbose_name="Duração (minutos)",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apresentacoes",
                        to="submissao.local",
                        verbose_name="Local",
                    ),
                ),
                (
                    "submissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apresentacoes",
                        to="submissao.submissao",
                        verbose_name="Submissão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apresentação",
                "verbose_name_plural": "Apresentações",
                "ordering": ["inicio"],
            },
        ),
        migrations.CreateModel(
            name="SubmissaoAutor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tipo_participacao",
                    models.CharField(
                        choices=[("Principal", "Principal"), ("Coautor", "Coautor")],
                        default="Coautor",
                        max_length=20,
                        verbose_name="Tipo de Participação",
                    ),
                ),
                (
                    "ordem_autoria",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ordem de aparição nos certificados e documentos.",
                        null=True,
                        verbose_name="Ordem de Autoria",
                    ),
                ),
                (
                    "lattes_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL do currículo Lattes do autor.",
                        max_length=500,
                        verbose_name="Currículo Lattes",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL do perfil LinkedIn do autor.",
                        max_length=500,
                        verbose_name="Perfil LinkedIn",
                    ),
                ),
                (
                    "afiliacao_institucional",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Universidade ou instituição de vínculo.",
                        max_length=255,
                        verbose_name="Afiliação Institucional",
                    ),
                ),
                (
                    "maiór_titulacao",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Grau acadêmico do autor (e.g., Mestrado, Doutorado).",
                        max_length=100,
                        verbose_name="Maior Titulação",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "submissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autores",
                        to="submissao.submissao",
                        verbose_name="Submissão",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissoes_como_coautor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autor de Submissão",
                "verbose_name_plural": "Autores de Submissão",
                "ordering": ["ordem_autoria", "criado_em"],
            },
        ),
        migrations.CreateModel(
            name="SubmissaoVersao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "numero_versao",
                    models.PositiveIntegerField(
                        help_text="Número sequencial de versão (1 para original, 2 para revisado, etc).",
                        verbose_name="Número da Versão",
                    ),
                ),
                (
                    "caminho_arquivo",
                    models.FileField(
                        help_text="Arquivo PDF ou DOCX enviado nesta versão.",
                        upload_to="submissoes/%Y/%m/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "submissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes",
                        to="submissao.submissao",
                        verbose_name="Submissão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão de Submissão",
                "verbose_name_plural": "Versões de Submissão",
                "ordering": ["numero_versao"],
            },
        ),
        migrations.AddIndex(
            model_name="submissao",
            index=models.Index(
                fields=["evento", "status"], name="submissao_s_evento__0a34bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissao",
            index=models.Index(
                fields=["autor_principal", "status"],
                name="submissao_s_autor_p_462c54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submissao",
            index=models.Index(
                fields=["area", "status"], name="submissao_s_area_id_5a6702_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avaliacao",
            index=models.Index(
                fields=["submissao", "status_parecer"],
                name="submissao_a_submiss_6dccac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="avaliacao",
            index=models.Index(
                fields=["avaliador", "status_parecer"],
                name="submissao_a_avaliad_41dde2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apresentacao",
            index=models.Index(
                fields=["local", "inicio"], name="submissao_a_local_i_9ffd80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apresentacao",
            index=models.Index(
                fields=["submissao", "inicio"], name="submissao_a_submiss_ae71cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submissaoautor",
            unique_together={("submissao", "usuario")},
        ),
        migrations.AlterUniqueTogether(
            name="submissaoversao",
            unique_together={("submissao", "numero_versao")},
        ),
    ]
