# Generated by Django 6.1.1 on 2026-09-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_evento_necessita_comprovante"),
        ("submissao", "0002_avaliador"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissao",
            name="sem_avaliador_disponivel",
            field=models.BooleanField(
                default=False,
                help_text="Marcado quando o sorteio não encontrou avaliadores elegíveis para esta submissão.",
                verbose_name="Sem Avaliador Disponível",
            ),
        ),
        migrations.CreateModel(
            name="AtribuicaoAvaliacao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Concluída", "Concluída"),
                            ("Cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="Pendente",
                        max_length=20,
                        verbose_name="Status da Atribuição",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        help_text="Avaliador sorteado para avaliar esta submissão.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atribuicoes",
                        to="submissao.avaliador",
                        verbose_name="Avaliador Sorteado",
                    ),
                ),
                (
                    "submissao",
                    models.OneToOneField(
                        help_text="Submissão designada para este avaliador.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atribuicao_avaliacao",
                        to="submissao.submissao",
                        verbose_name="Submissão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atribuição de Avaliação",
                "verbose_name_plural": "Atribuições de Avaliação",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["submissao", "status"],
                        name="submissao_a_submiss_999a38_idx",
                    ),
                    models.Index(
                        fields=["avaliador", "status"],
                        name="submissao_a_avaliad_839426_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AvaliadorEvento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        help_text="Avaliador vinculado ao evento pelo organizador.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_vinculados",
                        to="submissao.avaliador",
                        verbose_name="Avaliador",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        help_text="Evento em que o avaliador está habilitado a atuar.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliadores_vinculados",
                        to="eventos.evento",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliador do Evento",
                "verbose_name_plural": "Avaliadores do Evento",
                "ordering": ["avaliador__usuario__nome_completo"],
                "indexes": [
                    models.Index(
                        fields=["evento"], name="submissao_a_evento__1692e7_idx"
                    ),
                    models.Index(
                        fields=["avaliador"], name="submissao_a_avaliad_caef3a_idx"
                    ),
                ],
                "unique_together": {("evento", "avaliador")},
            },
        ),
    ]
